---
title: "Captain's Log"
author: "Samuel Pshyk"
date: "9/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## what does this command do?

This is the second page of my website. 

making a change seems to mean I need to knit the file again. 

I wonder how to make this pretty!
I wonder how long a line of text can take before it moves it to the next line on the displayed webpage. It seems weird to me that it would stretch out the length of it indefinitely but hey, I didn't design this program. I guess we'll see what happens when I load it.

## Captains log: commit 5

I've shown how to alter the title and the ## command will allow you to create a title. Still haven't filled out color. Is it possible to change the color of the text and its font? I will make a new page whose content will include nothing but the full lyrics of the Nickleback song photograph. I'm going to see if I can get the title section of the page without the assistance of the default R settings. 

## Captains log: commit 9 I think

I've decided to use my project to create a website to link useful documents that may be hard to find for other Yu-Gi-Oh judges. Im having some issues creating a new link to it though. As a personal note, if the name of a page is 2 or more words separated by a space, in the site directory, replace the spaces with underscores. 

## Captains log: commit 9. 
I miscounted the number of commits I had up to this point. We're actually on commit number 9. We added a link to the tournament policy document for the judging resource page. I'm going to continue to add all 3 policy documents and go from there. 

## Captains log: commit 10
the hyperlinks worked however they are not spaced correctly. Going to use this commit to fix this and add an image of the fast effect timing chart. Might consider adding a link to the most up to date version of the rule book.

## Captains log: commit 11
Dr. Arnholt suggested making new repositories for more parts of the website. Right now I plan on continuing with the main pages of the website and filling out more of the judge sections. The plan right now is to add a page for more recent rulings on card interactions and a section of PSCT. I guess I'm running into the issue of whether or not I want to include more info on the psct and make it more of an educational website for newer judges or a page for older ones who just want quick resources and less explanation. Im still debating on adding in a section about myself along with my judging history. 